DROP DATABASE IF EXISTS bankdb;
DROP USER IF EXISTS `bankadmin`@`%`;
DROP USER IF EXISTS `bankuser`@`%`;

CREATE DATABASE IF NOT EXISTS bankdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS `bankadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `bankdb`.* TO `bankadmin`@`%`;

CREATE USER IF NOT EXISTS `bankuser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `bankdb`.* TO `bankuser`@`%`;

FLUSH PRIVILEGES;